### ISSUE TITLE
No feedback from prediction.run()

### ISSUE THREAD

**Issue by MarcBarlett** [plantpredict/python-sdk#5]
plantpredict sdk prediction.run() will hang and never return a response but the website prediction log will show "Error"
![image](https://user-images.githubusercontent.com/58749850/157334319-424aabf9-b813-4833-b22c-70f3efd2825d.png)

**Comment by MarcBarlett** [comment]
`Traceback (most recent call last):
  File "C:\Users\FS100486\Documents\Python Scripts\NextGenAnalytics\src\nextgenanalytics\models\prediction_automation.py", line 130, in run_prediction
    prediction_details = prediction_to_clone.get()
  File "C:\Users\FS100486\Documents\Python Scripts\NextGenAnalytics\venv\lib\site-packages\plantpredict\prediction.py", line 155, in get
    return super(Prediction, self).get()
  File "C:\Users\FS100486\Documents\Python Scripts\NextGenAnalytics\venv\lib\site-packages\plantpredict\error_handlers.py", line 15, in function_wrapper
    return function(*args, **kwargs)
  File "C:\Users\FS100486\Documents\Python Scripts\NextGenAnalytics\venv\lib\site-packages\plantpredict\error_handlers.py", line 26, in function_wrapper
    response = function(*args, **kwargs)
  File "C:\Users\FS100486\Documents\Python Scripts\NextGenAnalytics\venv\lib\site-packages\plantpredict\plant_predict_entity.py", line 37, in get
    response = requests.get(
  File "C:\Users\FS100486\Documents\Python Scripts\NextGenAnalytics\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\FS100486\Documents\Python Scripts\NextGenAnalytics\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\FS100486\Documents\Python Scripts\NextGenAnalytics\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\FS100486\Documents\Python Scripts\NextGenAnalytics\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\FS100486\Documents\Python Scripts\NextGenAnalytics\venv\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\FS100486\Documents\Python Scripts\NextGenAnalytics\venv\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\FS100486\Documents\Python Scripts\NextGenAnalytics\venv\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\FS100486\Documents\Python Scripts\NextGenAnalytics\venv\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "c:\users\fs100486\appdata\local\programs\python\python39\lib\http\client.py", line 1345, in getresponse
    response.begin()
  File "c:\users\fs100486\appdata\local\programs\python\python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "c:\users\fs100486\appdata\local\programs\python\python39\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
KeyboardInterrupt`

**Comment by kurt-rhee** [comment]
Hello Marc, 

Apologies for the very long response time.  I just joined the PlantPredict team 2 months ago and am getting ramped up on maintenance of the SDK.  Are you still seeing issues with version 1.0.9?

**Comment by MarcBarlett** [comment]
Hey Kurt,
I haven't used the Plant Predict SDK in quite some time and have no idea if this is still an issue or not.
As it is stale I think we  can close the issue.
